title: Adhiansyah Ancha
author: Adhiansyah Ancha
email: coder.adhiansyah@outlook.com
description: > 
  Seorang pengguna Linux yang sedang mendalami bahasa 
  pemrograman Python dan pengembangan aplikasi Android. 
  Orangnya suka nasi gorang, mi instan, dan nasi gandul

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%d %B %Y, %R:%S:%N %z"  # Sesuai dengan strftime() Python: https://strftime.org/
  social_links:
    twitter: adhiansyahancha
    github:  adhiansyah
    rss: rss
    # facebook: jekyll
    # instagram: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
