# Berkas konfigurasi weblog

title: Adhiansyah Ancha
email: coder.adhiansyah@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Pengguan Fedora Linux yang menyukai nasi goreng dan mie instan. Ingin mendalami
  sistem operasi, terutama Linux dan Python untuk mempermudah hal-hal komputer yang biasa
url: "https://adhiansyah.github.io" 
github_username:  adhiansyah
twitter_username: adhiansyahancha
google_analytics: UA-154666828-1

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
